'use client';
import { useId, useRef, type ReactNode } from 'react';
import type { CompleteComparison } from '../lib/comparison-record';
import { FIELD_KEYS } from '../lib/rules';
export const fieldLabels = { brand:'Brand name', classType:'Class / type', abv:'Alcohol by volume', netContents:'Net contents', producer:'Producer name and address', origin:'Country of origin', warning:'Government warning' };
const observationLabels: Record<string,string> = { name:'Name',address:'Address',heading:'Heading',body:'Wording',headingBold:'Heading bold',bodyBold:'Body bold' };
export function observations(value: unknown): string {
  if (value == null) return 'Unknown';
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  if (typeof value !== 'object') return String(value);
  if ('status' in value && 'text' in value) return value.status === 'readable' && value.text ? String(value.text) : `${String(value.status).replaceAll('-', ' ')} — ${'reason' in value ? value.reason : 'No readable evidence'}`;
  return Object.entries(value).map(([key, child]) => `${observationLabels[key] ?? key}: ${observations(child)}`).join('\n');
}
export function EvidenceTable({record, resolution}:{record:CompleteComparison;resolution?:(key:typeof FIELD_KEYS[number])=>ReactNode}) {
 return <section aria-label="Comparison evidence"><h2>Seven-field comparison</h2><div className="comparison-table"><table><colgroup><col className="field"/><col className="evidence"/><col className="application"/><col className="result"/></colgroup><thead><tr><th>Field</th><th>Label evidence</th><th>Application / reference</th><th>Machine finding</th></tr></thead><tbody>{FIELD_KEYS.map(key=>{const field=record.comparison.fields[key];return <tr key={key} data-field={key} className={field.status==='mismatch'||field.status==='needs-review'?'flagged':''}><th scope="row">{fieldLabels[key]}</th><td data-title="Observed"><div>{key==='warning'?<><p>Government warning text and visible heading observations.</p><details className="wording-details"><summary>Read observed warning</summary>{observations(field.observed)}</details></>:observations(field.observed)}</div></td><td data-title="Reference"><div>{key==='warning'?<><p>Required warning wording and heading. Physical print size is not measured.</p><details className="wording-details"><summary>Read warning reference</summary>{field.expected}</details></>:key==='abv'?`${field.expected}% ABV`:field.expected}</div></td><td data-title="Finding"><div><strong className={`status ${field.status}`}>{field.status==='match'?'✓ ':field.status==='mismatch'?'≠ ':'! '}{field.status.replaceAll('-',' ')}</strong>{field.status==='match'?<details className="finding-details"><summary>Check details</summary><p className="help">{field.reasons.join(' ')}</p></details>:<p className="help">{field.reasons.join(' ')}</p>}{resolution?.(key)}</div></td></tr>;})}</tbody></table></div></section>;
}
export default function EvidenceReview({record,preview,previewNote,children,resolution,preserved=false}:{record:CompleteComparison;preview?:string|null;previewNote?:string;children?:ReactNode;resolution?:(key:typeof FIELD_KEYS[number])=>ReactNode;preserved?:boolean}) {
 const dialog=useRef<HTMLDialogElement>(null), id=useId();
 return <><div className="evidence-summary"><span className="pill">7 explicit fields</span><strong>Application {record.application.applicationId} / version {record.application.applicationVersion}</strong><span className="status needs-review">Human review required</span></div>
  <div className="workspace v3-workspace"><section aria-label="Label preview"><div className="preview-head"><h2>{preserved?'Preserved normalized label':record.source==='fixture'?'Synthetic label':'Uploaded label'}</h2><button disabled={!preview} onClick={()=>dialog.current?.showModal()}>Enlarge label</button></div><div className="label-stage">{preview?<img className="label-preview" src={preview} alt={preserved?'Preserved normalized label from saved review':record.source==='fixture'?'Exact synthetic label':'Original uploaded label'}/>:<p>Label preview unavailable. Do not infer image verification.</p>}</div><p className="evidence-note">{previewNote ?? 'Original selected image preview, not the server-normalized bytes. The comparison is bound to the sanitized image hash.'} Image-only review cannot verify physical print/type size.</p><details className="technical"><summary>Evidence provenance & technical details</summary><p className="hash">Source: {record.source} · Sanitized image SHA-256 {record.imageSha256}</p><pre>{JSON.stringify(record.evidence,null,2)}</pre></details></section><div className="comparison-column"><EvidenceTable record={record} resolution={resolution}/>{children}</div></div>
  <dialog ref={dialog} aria-labelledby={`${id}-zoom`}><div className="preview-head"><h2 id={`${id}-zoom`}>Larger label preview</h2><button onClick={()=>dialog.current?.close()}>Close preview</button></div>{preview&&<img className="label-preview" src={preview} alt="Enlarged label preview"/>}</dialog></>;
}
