'use client';
import {useEffect,useId,useRef,useState,type ReactNode} from 'react';
import {FIELD_KEYS} from '../lib/rules';
import {photoRecord,type UiCompleteComparison,type PhotoDescriptor,type PhotoPreview} from '../lib/live-photo-client';
export const fieldLabels={brand:'Brand name',classType:'Class / type',abv:'Alcohol by volume',netContents:'Net contents',producer:'Producer name and address',origin:'Country of origin',warning:'Government warning'};
const observationLabels:Record<string,string>={name:'Name',address:'Address',heading:'Heading',body:'Wording',headingBold:'Heading bold',bodyBold:'Body bold'};
export type GalleryProps={photos?:PhotoPreview[];loadPhoto?:(photo:PhotoDescriptor,variant:'original'|'normalized',signal:AbortSignal)=>Promise<Blob>};
export function observations(value:unknown):string {
 if(value==null)return 'Unknown';if(typeof value==='boolean')return value?'Yes':'No';if(typeof value!=='object')return String(value);
 if('status' in value&&'text' in value)return value.status==='readable'&&value.text?String(value.text):`${String(value.status).replaceAll('-',' ')}${value.text?` — ${String(value.text)}`:''} — ${'reason' in value?value.reason:'No readable evidence'}`;
 return Object.entries(value).map(([key,child])=>`${observationLabels[key]??key}: ${observations(child)}`).join('\n');
}
function SourceEvidence({record,field,onSelect}:{record:UiCompleteComparison;field:typeof FIELD_KEYS[number];onSelect?:(id:string)=>void}){
 const group=photoRecord(record);if(!group)return null;
 const leaves=Object.entries(group.provenance).filter(([path])=>path===field||path.startsWith(`${field}.`));
 function chips(ids:string[]){return ids.map(id=>{const photo=group!.photos.find(p=>p.photoId===id);return photo?<button type="button" className="source-chip" key={id} onClick={()=>onSelect?.(id)} aria-label={`View ${photo.role} photo ${photo.filename}`}>{photo.role} · {photo.filename}</button>:<span key={id}>Unknown photo source — do not verify</span>;});}
 return <div className="field-sources">{leaves.map(([path,p])=><div key={path}><span className="help">{observationLabels[path.split('.')[1]]??fieldLabels[field]} sources</span>{p.conflict&&<strong className="status mismatch">Conflicting photo observations</strong>}{p.variants.length?p.variants.map((v,i)=><div className="source-variant" key={i}>{p.conflict&&<q>{String(v.value)}</q>}{chips(v.sourcePhotoIds)}</div>):<p className="help">No contributing visible evidence in this photo set.</p>}</div>)}<details><summary>Per-photo observations</summary>{group.photoEvidence.photos.map(source=><div key={source.photoId}>{chips([source.photoId])}<p className="raw-observation">{observations(source.evidence[field])}</p></div>)}</details></div>;
}
export function EvidenceTable({record,resolution,onSelectPhoto}:{record:UiCompleteComparison;resolution?:(key:typeof FIELD_KEYS[number])=>ReactNode;onSelectPhoto?:(id:string)=>void}){
 return <section aria-label="Comparison evidence"><h2>Seven-field comparison</h2><div className="comparison-table"><table><colgroup><col className="field"/><col className="evidence"/><col className="application"/><col className="result"/></colgroup><thead><tr><th>Field</th><th>Label evidence</th><th>Application / reference</th><th>Machine finding</th></tr></thead><tbody>{FIELD_KEYS.map(key=>{const field=record.comparison.fields[key];return <tr key={key} data-field={key} className={field.status==='mismatch'||field.status==='needs-review'?'flagged':''}><th scope="row">{fieldLabels[key]}</th><td data-title="Observed"><div>{key==='warning'?<><p>Observed wording, heading and visible boldness; physical size is unverified.</p><details className="wording-details" open={field.status==='mismatch'}><summary>Read observed warning</summary>{observations(field.observed)}</details></>:observations(field.observed)}<SourceEvidence record={record} field={key} onSelect={onSelectPhoto}/></div></td><td data-title="Reference"><div>{key==='warning'?<><p>Required warning wording and heading. Physical print size is not measured.</p><details className="wording-details" open={field.status==='mismatch'}><summary>Read warning reference</summary>{field.expected}</details></>:key==='abv'?`${field.expected}% ABV`:field.expected}</div></td><td data-title="Finding"><div><strong className={`status ${field.status}`}>{field.status==='match'?'✓ ':field.status==='mismatch'?'≠ ':'! '}{field.status.replaceAll('-',' ')}</strong>{field.status==='match'?<details className="finding-details"><summary>Check details</summary>{field.reasons.map((reason,i)=><p className="help" key={i}>{reason}</p>)}</details>:field.reasons.map((reason,i)=><p className="help" key={i}>{reason}</p>)}{resolution?.(key)}</div></td></tr>;})}</tbody></table></div></section>;
}
export default function EvidenceReview({record,preview,previewNote,children,resolution,preserved=false,photos=[],loadPhoto}:{record:UiCompleteComparison;preview?:string|null;previewNote?:string;children?:ReactNode;resolution?:(key:typeof FIELD_KEYS[number])=>ReactNode;preserved?:boolean}&GalleryProps){
 const dialog=useRef<HTMLDialogElement>(null),stage=useRef<HTMLDivElement>(null),id=useId(),group=photoRecord(record);
 const [selected,setSelected]=useState(group?.photos[0]?.photoId??''),[variant,setVariant]=useState<'original'|'normalized'>(preserved?'normalized':'original');
 const [loaded,setLoaded]=useState<{key:string;url:string}|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const photo=group?.photos.find(p=>p.photoId===selected)??group?.photos[0],assetKey=`${photo?.photoId}:${variant}`;
 useEffect(()=>{setLoaded(null);setError('');setLoading(false);if(!loadPhoto||!photo)return;const controller=new AbortController();let url:string|undefined;setLoading(true);
  loadPhoto(photo,variant,controller.signal).then(blob=>{if(controller.signal.aborted)return;url=URL.createObjectURL(blob);setLoaded({key:assetKey,url});}).catch(()=>{if(!controller.signal.aborted)setError('This photo could not be retrieved or failed integrity verification. No substitute image is shown.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
  return()=>{controller.abort();if(url)URL.revokeObjectURL(url);};
 },[photo,variant,loadPhoto,assetKey]);
 const shown=group?(loadPhoto?(loaded?.key===assetKey?loaded.url:null):photos.find(p=>p.photoId===photo?.photoId)?.url??null):preview;
 function select(photoId:string){setSelected(photoId);stage.current?.focus({preventScroll:true});}
 const title=group?`${preserved?'Preserved':'Uploaded'} photos · ${group.photos.length} views · one bottle`:preserved?'Preserved normalized label':record.source==='fixture'?'Synthetic label':'Uploaded label';
 return <><div className="evidence-summary"><span className="pill">7 explicit fields</span><strong>Application {record.application.applicationId} / version {record.application.applicationVersion}</strong><span className="status needs-review">Human review required</span></div>
 <div className="workspace v3-workspace"><section aria-label="Label preview"><div className="preview-head"><h2>{title}</h2><button type="button" disabled={!shown} onClick={()=>dialog.current?.showModal()}>Enlarge label</button></div>
 {group&&<><div className="photo-rail" role="group" aria-label="Bottle photos">{group.photos.map((p,index)=><button type="button" key={p.photoId} aria-pressed={p.photoId===photo?.photoId} onClick={()=>select(p.photoId)}>{!preserved&&photos.find(v=>v.photoId===p.photoId)?.url&&<img src={photos.find(v=>v.photoId===p.photoId)!.url} alt=""/>}<span>{index+1}. {p.role} · {p.filename}</span></button>)}</div>{loadPhoto&&<div className="actions" role="group" aria-label="Preserved image variant">{(['original','normalized'] as const).map(v=><button type="button" key={v} aria-pressed={v===variant} onClick={()=>setVariant(v)}>{v==='original'?'Original upload':'Normalized analysis image'}</button>)}</div>}</>}
 <div className="label-stage" ref={stage} tabIndex={-1} aria-label="Selected photo preview">{loading?<p role="status">Loading selected {variant} photo…</p>:shown?<img className="label-preview" src={shown} alt={group?`${photo?.role} · ${photo?.filename} · ${variant}`:preserved?'Preserved normalized label from saved review':record.source==='fixture'?'Exact synthetic label':'Original uploaded label'}/>:<p>Label preview unavailable. Do not infer image verification.</p>}</div>{error&&<p role="alert">{error}</p>}
 <p className="evidence-note">{group?(preserved?'Each selected original or normalized asset is verified against its saved hash, byte count and MIME.':'Original selected photo previews, not server-normalized bytes. All photos contribute to one bound comparison.'):previewNote??'Original selected image preview, not the server-normalized bytes. The comparison is bound to the sanitized image hash.'} Image-only review cannot verify physical print/type size.</p>{preserved&&!group&&<p className="help">Original upload was not retained for this historical review. Only the normalized image is available.</p>}
 <details className="technical"><summary>Evidence provenance & technical details</summary><p className="hash">Source: {record.source} · {group?'Photo-set':'Sanitized image'} SHA-256 {group?.photoSetSha256??record.imageSha256}</p>{photo&&<p className="hash">Original SHA-256 {photo.sourceSha256}<br/>Normalized SHA-256 {photo.normalized.sha256}</p>}<pre>{JSON.stringify(group?{photos:group.photos,provenance:group.provenance,photoEvidence:group.photoEvidence}:record.evidence,null,2)}</pre></details></section><div className="comparison-column"><EvidenceTable record={record} resolution={resolution} onSelectPhoto={select}/>{children}</div></div>
 <dialog ref={dialog} aria-labelledby={`${id}-zoom`}><div className="preview-head"><h2 id={`${id}-zoom`}>Larger label preview</h2><button onClick={()=>dialog.current?.close()}>Close preview</button></div>{shown&&<img className="label-preview" src={shown} alt="Enlarged label preview"/>}</dialog></>;
}
