import { createReviewHandler } from '../../../../lib/review-route';
export const runtime='nodejs';
export const dynamic='force-dynamic';
export const POST=createReviewHandler();
export const GET=POST;
export const PUT=POST;
export const PATCH=POST;
export const DELETE=POST;
export const OPTIONS=POST;
export const HEAD=POST;
