import { afterEach, expect, test, vi } from 'vitest';
import { rmSync } from 'node:fs';
import { privateLedgerDir } from './fixtures/private-ledger';
import { join } from 'node:path';
import { createDemoHandler } from '../lib/demo-route';
import { SqliteSpendStore } from '../lib/sqlite-spend';
import fixtures from './fixtures/comparisons.json';
import { image } from './fixtures/synthetic';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import PairInput from '../components/PairInput';
const dirs: string[] = [];
vi.setConfig({ testTimeout: 60_000 }); // Real Windows ACL checks are not mocked/skipped.
afterEach(() => { for (const d of dirs.splice(0)) rmSync(d, { recursive: true, force: true }); });
const secret = 'synthetic-only-access-code-0123456789abcdef';
test('access secret is user-entered, never rendered from the server environment',()=>{vi.stubEnv('TTB_DEMO_ACCESS_SECRET',secret);try{const html=renderToStaticMarkup(createElement(PairInput));expect(html).toContain('type="password"');expect(html).not.toContain(secret);}finally{vi.unstubAllEnvs();}});
test('each missing required configuration closes before reading body',async()=>{const {env,transport}=setup();for(const key of Object.keys(env)){const req=await request();expect((await createDemoHandler({env:{...env,[key]:undefined},transport})(req)).status).toBe(403);expect(req.bodyUsed).toBe(false);}expect(transport).not.toHaveBeenCalled();});
test('chunked body without content-length is capped before multipart decoding',async()=>{const {handler,transport}=setup();const req=new Request('https://demo.example/api/comparisons',{method:'POST',headers:{origin:'https://demo.example','x-ttb-demo-code':secret,'content-type':'multipart/form-data; boundary=x'},body:new ReadableStream({start(c){c.enqueue(new Uint8Array(11*1024*1024));c.close();}}),duplex:'half'} as RequestInit);expect((await handler(req)).status).toBe(413);expect(transport).not.toHaveBeenCalled();});
function setup(bad = false) {
 const dir = privateLedgerDir(); dirs.push(dir);
 const path = join(dir, 'spend.sqlite'); SqliteSpendStore.provision(path);
 const transport = vi.fn(async (url: string) => url.endsWith('/models') ? Response.json({data:[{id:'anthropic/claude-haiku-4.5',context_length:200000,pricing:{prompt:'0.000001',completion:'0.000005',image:'0',request:'0'}}]}) : Response.json({choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content:bad ? '{}' : JSON.stringify(fixtures.evidence)}}]}));
 const env = {TTB_DEMO_ENABLED:'true',TTB_DEMO_ACCESS_SECRET:secret,TTB_DEMO_ORIGIN:'https://demo.example',TTB_DEMO_DATA_DIR:dir,TTB_DEMO_PERSISTENT_VOLUME:'single-private-volume-v1',OPENROUTER_API_KEY:'synthetic-key'};
 return {handler:createDemoHandler({env,transport}),transport,env,path};
}
async function request(app: unknown = fixtures.application) { const form = new FormData(); form.set('image',new File([new Uint8Array(await image())],'label.png',{type:'image/png'})); form.set('application',JSON.stringify(app)); return new Request('https://demo.example/api/comparisons',{method:'POST',headers:{origin:'https://demo.example','x-ttb-demo-code':secret},body:form}); }
test('missing config and unauthorized deny before reading body or transport', async () => { const {handler,transport} = setup(); const req = await request(); req.headers.delete('x-ttb-demo-code'); const spy = vi.spyOn(req,'formData'); expect((await handler(req)).status).toBe(403); expect(req.bodyUsed).toBe(false); expect(spy).not.toHaveBeenCalled(); expect(transport).not.toHaveBeenCalled(); expect((await createDemoHandler({env:{}})(await request())).status).toBe(403); });
test('exact origin, schema, oversized and malformed chunked input fail closed',async()=>{const {handler,transport}=setup(); const cross=await request();cross.headers.set('origin','https://evil.example');expect((await handler(cross)).status).toBe(403); const big=await request();big.headers.set('content-length','999999999');expect((await handler(big)).status).toBe(413); expect((await handler(await request({...fixtures.application,authorized:true}))).status).toBe(400); const chunked=new Request('https://demo.example/api/comparisons',{method:'POST',headers:{origin:'https://demo.example','x-ttb-demo-code':secret,'content-type':'multipart/form-data; boundary=x'},body:new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('invalid'));c.close();}}),duplex:'half'} as RequestInit);expect((await handler(chunked)).status).toBe(400);expect(transport).not.toHaveBeenCalled();});
test('synthetic route -> real Haiku adapter transport -> real rules and provenance',async()=>{const {handler,transport}=setup();const response=await handler(await request());expect(response.status).toBe(200);const value=await response.json();expect(value.result.processing).toBe('complete');expect(value.result.source).toBe('openrouter');expect(value.result.comparison.fields.brand.status).toBe('match');expect(value.elapsedMs).toBeGreaterThanOrEqual(0);expect(transport).toHaveBeenCalledTimes(2);});
test('bad evidence never returns a match and does not release spend',async()=>{const {handler,path}=setup(true);const response=await handler(await request());const value=await response.json();expect(value.result.processing).toBe('failed');expect(value.result).not.toHaveProperty('comparison');const store=new SqliteSpendStore(path);expect(store.totals().unresolvedMicrousd).toBe(1000000);store.close();});
test('observed Haiku catalog cache prices allow bounded tool-free dispatch',async()=>{const {env,transport}=setup();transport.mockImplementationOnce(async()=>Response.json({data:[{id:'anthropic/claude-haiku-4.5',context_length:200000,pricing:{prompt:'0.000001',completion:'0.000005',web_search:'0.01',input_cache_read:'0.0000001',input_cache_write:'0.00000125',input_cache_write_1h:'0.000002'}}]}));const response=await createDemoHandler({env,transport})(await request());expect(response.status).toBe(200);expect(transport).toHaveBeenCalledTimes(2);});
test('unknown paid fee still refuses dispatch',async()=>{const {env}=setup();const transport=vi.fn(async()=>Response.json({data:[{id:'anthropic/claude-haiku-4.5',context_length:200000,pricing:{prompt:'0.000001',completion:'0.000005',unreviewed_fee:'0.01'}}]}));const response=await createDemoHandler({env,transport})(await request());expect((await response.json()).result.processing).toBe('failed');expect(transport).toHaveBeenCalledTimes(1);});
test('catalog price drift denies paid dispatch',async()=>{const {env}=setup();const transport=vi.fn(async()=>Response.json({data:[{id:'anthropic/claude-haiku-4.5',context_length:200001,pricing:{prompt:'0.000002',completion:'0.000005'}}]}));const response=await createDemoHandler({env,transport})(await request());expect((await response.json()).result.processing).toBe('failed');expect(transport).toHaveBeenCalledTimes(1);});
