import {test,expect} from '@playwright/test';
import {latestGroupSnapshot} from './read-group-snapshot';
import {spawn,type ChildProcess} from 'node:child_process';
import {createServer} from 'node:net';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {ReviewStore} from '../../lib/review-store';
import {SqliteSpendStore} from '../../lib/sqlite-spend';
import {compareApplication} from '../../lib/rules';
import {checkedRecord,newReviewIntent} from '../../lib/review-policy';
import {photoRecord} from '../../lib/live-photo-client';
import type {CompleteComparison} from '../../lib/comparison-record';
const fixtures=JSON.parse(readFileSync(new URL('../fixtures/comparisons.json',import.meta.url),'utf8'));
const historical=JSON.parse(readFileSync(new URL('../fixtures/rules-v1-records.json',import.meta.url),'utf8'));
const hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex');

test('real guarded synthetic Single + Batch groups, old history, restart and every private original/normalized hash',async({page},info)=>{
 test.setTimeout(180000);
 const output=info.outputPath('durable');mkdirSync(output,{recursive:true});
 const root=mkdtempSync(join(output,'private-')),spend=join(root,'spend'),reviews=join(root,'reviews');mkdirSync(spend,{mode:0o700});mkdirSync(reviews,{mode:0o700});
 const db=join(reviews,'reviews.sqlite');SqliteSpendStore.provision(join(spend,'spend.sqlite'));ReviewStore.provision(db);
 const png=readFileSync('public/offline-samples/match.png'),back=readFileSync('public/offline-samples/discrepancy.png');
 // Seed genuinely old revisions BEFORE the additive migration. Preserve exact receipts.
 const legacyStore=new ReviewStore(db),oldRecords:CompleteComparison[]=[],oldReceipts=[];
 for(const revision of [1,2]){
  const r=structuredClone(historical[0].record);r.application.applicationId='HISTORICAL-'+revision;r.imageSha256=hash(png);r.comparison.applicationId=r.application.applicationId;
  const record=revision===1?r:{...r,comparison:compareApplication(r.application as never,r.evidence)};
  const valid=checkedRecord(record);if(!valid)throw Error('Invalid historical fixture');
  const id=legacyStore.snapshot(valid,png,'image/png');oldRecords.push(valid);oldReceipts.push(legacyStore.save({comparisonId:id,idempotencyKey:randomUUID(),intent:{...newReviewIntent(valid),outcome:'second-review',confirmed:true,notes:'Historical synthetic saved decision.'}}));
 }
 legacyStore.close();ReviewStore.migratePhotos(db);
 const listener=createServer();await new Promise<void>(r=>listener.listen(0,'127.0.0.1',r));const port=(listener.address() as {port:number}).port;await new Promise<void>(r=>listener.close(()=>r()));
 const origin=`http://localhost:${port}`,code=randomUUID();let child:ChildProcess|undefined,log='';const pids:number[]=[],api:unknown[]=[],errors:string[]=[];
 // Whitelisted disposable configuration: no inherited cloud keys, hosted mode or paid transport.
 const env={NODE_ENV:'production' as const,PATH:process.env.PATH,HOME:process.env.HOME,NODE_OPTIONS:'--max-old-space-size=512',NEXT_TELEMETRY_DISABLED:'1',TTB_TEST_PORT:String(port),TTB_TEST_DISPOSABLE:'yes',TTB_DEMO_ENABLED:'true',TTB_DEMO_ACCESS_SECRET:code,TTB_DEMO_ORIGIN:origin,TTB_DEMO_DATA_DIR:spend,TTB_REVIEW_DATA_DIR:reviews,TTB_MEDIA_SIGNING_SECRET:randomUUID(),TTB_DEMO_PERSISTENT_VOLUME:'single-private-volume-v1',OPENROUTER_API_KEY:'synthetic-unused-key'};
 async function start(){child=spawn(process.execPath,['--import','tsx','tests/fixtures/durable-server.ts'],{cwd:process.cwd(),env,stdio:['ignore','pipe','pipe']});pids.push(child.pid!);await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Readiness timeout '+log)),45000);child!.once('exit',code=>{clearTimeout(timer);reject(Error('Service exit '+code+' '+log));});child!.stdout!.on('data',b=>{const text=String(b);log+=text;if(text.includes('READY pid=')){clearTimeout(timer);resolve();}});child!.stderr!.on('data',b=>log+=String(b));});}
 async function stop(){if(child&&child.exitCode===null){const c=child;await new Promise<void>(r=>{c.once('exit',()=>r());c.kill('SIGTERM');});}}
 async function verify(){await expect(page.getByText('✓ Public demo access',{exact:true})).toBeVisible();await expect(page.locator('input[type=password]')).toHaveCount(0);}
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{const path=new URL(r.url()).pathname;if(path.startsWith('/api/'))api.push({path,status:r.status()});});page.on('requestfailed',r=>api.push({path:new URL(r.url()).pathname,failure:r.failure()?.errorText}));
 try{
  await start();await page.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());await page.goto(origin+'/review');await verify();
  const source=page.getByLabel('Input source');if(await source.count())await source.selectOption('manual');
  await page.getByLabel('Label image (JPEG or PNG)',{exact:true}).setInputFiles([{name:'front.png',mimeType:'image/png',buffer:png},{name:'back.png',mimeType:'image/png',buffer:back}]);await page.getByLabel('Role for front.png').selectOption('front');await page.getByLabel('Role for back.png').selectOption('back');await page.locator('#entry-application-tab').click();
  const application={...fixtures.application,applicationId:'DURABLE-WINE-GROUP',commodity:'wine',classType:'Wine',imported:false,origin:{kind:'domestic',country:'US'}};
  for(const key of ['applicationId','applicationVersion','brand','classType','abv','netContents','producerName','producerAddress'] as const)await page.locator('#'+key).fill(String(application[key]));await page.locator('#commodity').selectOption('wine');await page.locator('#imported').selectOption('false');await page.locator('#originKind').selectOption('domestic');await page.locator('#country').fill('US');
  await page.getByRole('button',{name:'Submit for comparison',exact:true}).click();await expect(page.getByRole('region',{name:'Live comparison results'}).getByRole('table')).toBeVisible();const compared=latestGroupSnapshot(db);expect(compared.result.comparison.rulesRevision).toBe(6);expect(compared.result.aggregationVersion).toBe('photo-set-aggregation-v2');expect(compared.result.photos).toHaveLength(2);
  const result=page.getByRole('region',{name:'Live comparison results'});await expect(result.getByRole('table')).toBeVisible();await expect(result.locator('[data-field=classType]')).toContainText('broad-class');expect(compared.result.comparison.fields.classType.status).toBe('match');expect(compared.result.comparison.fields.origin.status).toBe('not-applicable');expect(compared.result.provenance['warning.body'].sourcePhotoIds).toEqual([compared.result.photos[1].photoId]);expect(compared.result.provenance.brand.sourcePhotoIds).toEqual([compared.result.photos[0].photoId]);await expect(result.getByRole('radio',{name:'Pass',exact:true})).toBeDisabled();
  await result.getByRole('radio',{name:'Second reviewer',exact:true}).check();await result.getByLabel('Correction / escalation notes').fill('Synthetic complementary wine photos: request physical review.');await result.getByRole('checkbox',{name:/I reviewed this exact/}).check();
  const saves:unknown[]=[];await page.route('**/api/reviews',async route=>{saves.push(route.request().postDataJSON());if(saves.length===1){expect((await route.fetch()).status()).toBe(200);return route.abort('failed');}return route.continue();});
  await result.getByRole('button',{name:'Submit review',exact:true}).click();await expect(result.getByRole('alert')).toContainText('UNSAVED');await result.getByRole('button',{name:'Submit review',exact:true}).click();await expect(result.getByTestId('saved-review')).toBeVisible();expect(saves[1]).toEqual(saves[0]);await page.unroute('**/api/reviews');await page.screenshot({path:join(output,'single-saved.png'),fullPage:true});
  // One two-photo Batch bottle, intentionally contradictory back observation.
  await page.getByRole('tab',{name:'Batch upload',exact:true}).click();const panel=page.locator('#batch-panel');const mode=panel.getByLabel('Batch execution mode');if(await mode.count())await mode.selectOption('live');await panel.getByLabel('Batch label images',{exact:true}).setInputFiles([{name:'front.png',mimeType:'image/png',buffer:png},{name:'back.png',mimeType:'image/png',buffer:back}]);await panel.getByRole('tab',{name:'Application',exact:true}).click();
  const mapping={schemaVersion:2,groups:[{groupId:randomUUID(),application:{...application,applicationId:'DURABLE-CONFLICT'},photos:[{photoId:randomUUID(),filename:'front.png',role:'front'},{photoId:randomUUID(),filename:'back.png',role:'closeup'}]}]};await panel.getByLabel('Application manifest file (JSON)').setInputFiles({name:'mapping.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(mapping))});await panel.getByRole('button',{name:'Validate batch manifest'}).click();await panel.getByRole('button',{name:'Start live batch',exact:true}).click();await expect(panel.getByTestId('batch-summary')).toContainText('Compared: 1');await panel.getByRole('button',{name:'Open review',exact:true}).click();const active=panel.getByTestId('active-pair'),row=active.locator('[data-field=abv]');await expect(row).toContainText('Conflicting photo observations');await row.getByText('Resolve this field',{exact:true}).click();await row.getByLabel('Human resolution for Alcohol by volume',{exact:true}).selectOption('confirmed-mismatch');await row.getByLabel('Resolution reason for Alcohol by volume').fill('Synthetic independently confirmed discrepancy.');await row.getByRole('button',{name:'Confirm resolution for Alcohol by volume'}).click();await expect(row.getByTestId('resolved-abv')).toContainText('locally confirmed');await expect(row.locator('[data-title=Finding] strong.status.mismatch')).toBeVisible();await expect(active.getByRole('radio',{name:'Pass',exact:true})).toBeDisabled();await active.getByRole('radio',{name:'Request correction',exact:true}).check();await active.getByLabel('Correction / escalation notes').fill('Synthetic confirmed conflict requires corrected evidence.');await active.getByRole('checkbox',{name:/I reviewed this exact/}).check();await active.getByRole('button',{name:'Submit review',exact:true}).click();await expect(active.getByTestId('saved-review')).toBeVisible();await page.screenshot({path:join(output,'batch-conflict-saved.png'),fullPage:true});
  await stop();await start();expect(pids[1]).not.toBe(pids[0]);await page.reload();await verify();await page.getByRole('button',{name:'Load saved reviews',exact:true}).click();
  const store=new ReviewStore(db),list=store.list();expect(list).toHaveLength(4);const proof:unknown[]=[];
  for(const saved of list){const detail=store.detail(saved.receipt.reviewId),group=photoRecord(detail.record);await page.getByRole('button',{name:`Reopen ${saved.application.applicationId} / ${saved.application.applicationVersion} — ${saved.outcome}`,exact:true}).click();const reopened=page.getByTestId('reopened-review');await expect(reopened.getByRole('table')).toBeVisible();
   if(group){if(group.application.applicationId==='DURABLE-WINE-GROUP')expect(group).toEqual(compared.result);else {await expect(reopened.locator('[data-field=abv]')).toContainText('Resolved');await expect(reopened.locator('[data-field=abv] [data-title=Finding] strong.status.mismatch')).toBeVisible();}
    for(const photo of group.photos){await reopened.getByRole('group',{name:'Bottle photos'}).getByRole('button',{name:new RegExp(photo.filename)}).click();for(const variant of ['original','normalized'] as const){await reopened.getByRole('button',{name:variant==='original'?'Original upload':'Normalized analysis image',exact:true}).click();const image=reopened.getByAltText(`${photo.role} · ${photo.filename} · ${variant}`,{exact:true});await expect(image).toBeVisible();expect(await image.evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true);const asset=store.evidence(saved.receipt.reviewId,{photoId:photo.photoId,variant}),expected=variant==='original'?photo.sourceSha256:photo.normalized.sha256;expect(hash(asset.bytes)).toBe(expected);if(variant==='original')expect(asset.bytes).toEqual(photo.filename==='front.png'?png:back);const denied=await fetch(origin+`/api/reviews/${saved.receipt.reviewId}/photos/${photo.photoId}/${variant}/evidence`,{method:'POST',headers:{origin}});expect(denied.status).toBe(403);proof.push({reviewId:saved.receipt.reviewId,photoId:photo.photoId,variant,sha256:hash(asset.bytes),bytes:asset.bytes.length,unauthenticated:denied.status});}}
   }else {const index=oldReceipts.findIndex(r=>r.reviewId===saved.receipt.reviewId);expect(detail.record).toEqual(oldRecords[index]);expect(saved.receipt).toEqual(oldReceipts[index]);await expect(reopened).toContainText('Original upload was not retained');expect(hash(store.evidence(saved.receipt.reviewId).bytes)).toBe(hash(png));}
   await page.screenshot({path:join(output,`reopened-${saved.application.applicationId}.png`),fullPage:true});
  }
  store.close();expect((log.match(/SYNTHETIC_PROVIDER_CALL/g)||[]).length).toBe(2);expect(errors).toEqual([]);writeFileSync(join(output,'proof.json'),JSON.stringify({provenance:'LOCAL GUARDED SYNTHETIC PROVIDER; REAL ROUTES, SQLITE, BROWSER AND PROCESS RESTART; NO PAID CALLS',pids,oldReceipts,proof,api,errors,identicalRetry:true,providerCalls:2},null,2));
 }finally{await stop();writeFileSync(join(output,'service.log'),log);writeFileSync(join(output,'diagnostics.json'),JSON.stringify({api,errors,alerts:await page.getByRole('alert').allTextContents().catch(()=>[])},null,2));}
});
