import {test,expect,verifyAccess,PUBLIC_DEMO_SESSION} from './ui-diagnostics';
import type {Page,Route} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
const fixtures=JSON.parse(readFileSync(new URL('../fixtures/photo-ui-records.json',import.meta.url),'utf8'));
import {photoSetCanonical,type PhotoGroupDeclaration,type PreparedGroup} from '../../lib/photo-contracts';
import type {CompletePhotoComparison} from '../../lib/live-photo-client';
const code='synthetic-photo-ui-session',comparisonId='00000000-0000-4000-8000-000000000041',reviewId='00000000-0000-4000-8000-000000000042';
const bytes=[readFileSync('public/offline-samples/match.png'),readFileSync('public/offline-samples/discrepancy.png')];
const uploads=bytes.map((buffer,i)=>({name:i?'back.png':'front.png',mimeType:'image/png',buffer}));
const base=fixtures.conflict as unknown as CompletePhotoComparison;
const receipt={state:'SAVED',comparisonId,reviewId,savedAt:'2026-09-22T12:00:00Z',identity:'Public demo use — NOT an individually authenticated reviewer'};
function bound(group:PhotoGroupDeclaration,conflict=true){
 const original=(conflict?fixtures.conflict:fixtures.complementary) as unknown as CompletePhotoComparison;
 let text=JSON.stringify(original);original.photos.forEach((p,i)=>text=text.replaceAll(p.photoId,group.photos[i].photoId));
 const record=JSON.parse(text) as CompletePhotoComparison;record.groupId=group.groupId;record.revision=group.revision;record.application=group.application;
 record.comparison.applicationId=group.application.applicationId;record.comparison.applicationVersion=group.application.applicationVersion;
 record.photos=record.photos.map((p,i)=>({...p,...group.photos[i]}));record.photoSetSha256=createHash('sha256').update(photoSetCanonical(record.photos)).digest('hex');
 const prepared:PreparedGroup={schemaVersion:2,groupId:group.groupId,revision:group.revision,photos:record.photos,photoSetSha256:record.photoSetSha256,attemptId:randomUUID(),reservationId:randomUUID(),binding:record.photoSetSha256+'.'+'a'.repeat(64)};return {record,prepared};
}
async function requestGroup(route:Route){const request=route.request(),body=await new Response(new Uint8Array(request.postDataBuffer()!),{headers:{'content-type':request.headers()['content-type']}}).formData();return {group:JSON.parse(String(body.get('group'))) as PhotoGroupDeclaration,operation:JSON.parse(String(body.get('operation'))),body};}
async function enter(page:Page){await page.goto('/review');const mode=page.getByLabel('Input source');if(await mode.count())await mode.selectOption('manual');}
async function application(page:Page){await page.locator('#entry-application-tab').click();for(const key of ['applicationId','applicationVersion','brand','classType','abv','netContents','producerName','producerAddress'] as const)await page.locator(`#${key}`).fill(String(base.application[key]));await page.locator('#commodity').selectOption(base.application.commodity);await page.locator('#imported').selectOption(String(base.application.imported));await page.locator('#originKind').selectOption(base.application.origin.kind);await page.locator('#country').fill(base.application.origin.country);}
async function input(page:Page){await page.getByLabel('Label image (JPEG or PNG)',{exact:true}).setInputFiles(uploads);await page.getByLabel('Role for front.png').selectOption('front');await page.getByLabel('Role for back.png').selectOption('back');await application(page);}
async function mock(page:Page,options:{delayPrepare?:Promise<void>;delaySave?:Promise<void>}={}){
 const prepared=new Map<string,ReturnType<typeof bound>>();let executes=0,saves=0,last:CompletePhotoComparison|undefined,intent:unknown;
 await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;expect(route.request().headers()['x-ttb-demo-code']).toBe(PUBLIC_DEMO_SESSION);
 if(path==='/api/reviews/list')return route.fulfill({json:{reviews:saves&&last?[{receipt,application:last.application,outcome:'correction'}]:[]}});
 if(path==='/api/comparisons'){const {group,operation,body}=await requestGroup(route);expect([...body.keys()]).toEqual(['group','operation',...group.photos.map(p=>'photo:'+p.photoId)]);expect(route.request().headers()['x-ttb-batch-intent']).toBeUndefined();
 if(operation.phase==='prepare'){const result=bound(group);prepared.set(group.groupId,result);await options.delayPrepare;return route.fulfill({json:{prepared:result.prepared}}).catch(()=>{});}
 const result=prepared.get(group.groupId)!;expect(operation).toEqual({phase:'execute',attemptId:result.prepared.attemptId,reservationId:result.prepared.reservationId,binding:result.prepared.binding});executes++;last=result.record;return route.fulfill({json:{result:last,comparisonId,reviewAvailability:'available',elapsedMs:12}});}
 if(path==='/api/reviews'){saves++;intent=route.request().postDataJSON().intent;await options.delaySave;return route.fulfill({json:{receipt}}).catch(()=>{});}
 if(path===`/api/reviews/${reviewId}`)return route.fulfill({json:{receipt,record:last,intent}});
 if(path.includes(`/api/reviews/${reviewId}/photos/`)){const photo=last!.photos.find(p=>path.includes(p.photoId))!;return route.fulfill({body:bytes[last!.photos.indexOf(photo)],contentType:'image/png'});}
 return route.abort();});return {get executes(){return executes;},get saves(){return saves;}};
}
test.beforeEach(async({page,baseURL},info)=>{await page.setViewportSize({width:info.project.name==='mobile'?390:1440,height:900});await page.route('**/*',route=>new URL(route.request().url()).origin===new URL(baseURL!).origin?route.continue():route.abort());});
test('photo intake preserves independent application, roles/order and four-photo limit without network work',async({page})=>{
 let calls=0;await page.route('**/api/**',route=>{calls++;return route.abort();});await enter(page);
 const file=page.getByLabel('Label image (JPEG or PNG)',{exact:true});await file.setInputFiles([...uploads,...uploads.map((p,i)=>({...p,name:`extra-${i}.png`}))]);await expect(page.getByRole('button',{name:'Add another photo',exact:true})).toBeDisabled();await expect(page.locator('.photo-editor-item')).toHaveCount(4);await expect(page.locator('#brand')).not.toBeVisible();
 await file.setInputFiles({name:'fifth.png',mimeType:'image/png',buffer:bytes[0]});await expect(page.locator('#single-panel').getByRole('alert')).toContainText('1–4');await page.getByRole('button',{name:'Remove extra-1.png',exact:true}).click();await page.getByLabel('Role for back.png').selectOption('back');await page.getByRole('button',{name:'Move back.png earlier',exact:true}).click();await expect(page.locator('.photo-editor-item').first()).toContainText('back.png');await expect(page.getByRole('button',{name:'Add another photo',exact:true})).toBeEnabled();expect(calls).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('Single sends one identified photo group, shows source/conflict candidates and real measured stages',async({page},info)=>{
 const counters=await mock(page);await enter(page);await verifyAccess(page,code);await input(page);await page.getByRole('button',{name:'Submit for comparison',exact:true}).click();const results=page.getByRole('region',{name:'Live comparison results'});await expect(results.getByRole('table')).toBeVisible();expect(counters.executes).toBe(1);
 const row=results.locator('[data-field=abv]');await expect(row).toContainText('Conflicting photo observations');await expect(row).toContainText('45%');await row.getByRole('button',{name:'View back photo back.png'}).first().click();await expect(results.getByAltText('back · back.png · original',{exact:true})).toBeVisible();await expect(results.getByRole('group',{name:'Bottle photos'}).getByRole('button')).toHaveCount(2);await expect(results.locator('pre:visible')).toHaveCount(0);await expect(page.getByRole('status').filter({hasText:'Joint comparison & snapshot'})).toContainText(/\d+ ms/);
 await results.getByRole('button',{name:'Enlarge label'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('synthetic-multiphoto-conflict.png'),fullPage:true});
});
test('editing only secondary photo while preparation is pending discards late preparation and never executes',async({page})=>{
 let release!:()=>void;const hold=new Promise<void>(r=>release=r),counters=await mock(page,{delayPrepare:hold});await enter(page);await verifyAccess(page,code);await input(page);await page.getByRole('button',{name:'Submit for comparison',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Image validation & preparation'})).toBeVisible();await page.locator('#entry-images-tab').click();await page.getByRole('button',{name:'Remove back.png',exact:true}).click();release();await expect(page.getByRole('button',{name:'Submit for comparison',exact:true})).toBeEnabled();await expect(page.getByRole('region',{name:'Live comparison results'})).toHaveCount(0);expect(counters.executes).toBe(0);
});
test('field resolution is explicit, note-gated, adjacent to unchanged AI status, and editing removes Resolved',async({page})=>{
 await mock(page);await enter(page);await verifyAccess(page,code);await input(page);await page.getByRole('button',{name:'Submit for comparison',exact:true}).click();const row=page.locator('[data-field=abv]');await expect(row).toContainText('mismatch');await row.getByText('Resolve this field',{exact:true}).click();await row.getByLabel('Human resolution for Alcohol by volume',{exact:true}).selectOption('confirmed-mismatch');await expect(row.getByTestId('resolved-abv')).toHaveCount(0);const button=row.getByRole('button',{name:'Confirm resolution for Alcohol by volume'});await expect(button).toBeDisabled();await row.getByLabel('Resolution reason for Alcohol by volume').fill('Synthetic independent confirmation of actual discrepancy.');await expect(button).toBeEnabled();await expect(row.getByTestId('resolved-abv')).toHaveCount(0);await button.click();await expect(row.getByTestId('resolved-abv')).toContainText('locally confirmed, UNSAVED');await expect(row.locator('[data-title=Finding] strong.status.mismatch')).toBeVisible();await expect(page.getByRole('radio',{name:'Pass',exact:true})).toBeDisabled();await row.getByLabel('Resolution reason for Alcohol by volume').fill('Changed synthetic supporting assessment.');await expect(row.getByTestId('resolved-abv')).toHaveCount(0);
});
test('@integration one saved bottle reopens every original/normalized photo after refresh without new comparisons',async({page})=>{
 const counters=await mock(page);await enter(page);await verifyAccess(page,code);await input(page);await page.getByRole('button',{name:'Submit for comparison',exact:true}).click();const results=page.getByRole('region',{name:'Live comparison results'});await expect(results.getByRole('table')).toBeVisible();await results.getByRole('radio',{name:'Request correction',exact:true}).check();await results.getByLabel('Correction / escalation notes').fill('Synthetic correction request for conflicting photo evidence.');await results.getByRole('checkbox',{name:/I reviewed this exact/}).check();await results.getByRole('button',{name:'Submit review',exact:true}).click();await expect(results.getByTestId('saved-review')).toBeVisible();await page.reload();await verifyAccess(page,code);await page.getByRole('button',{name:'Load saved reviews'}).click();await page.getByRole('button',{name:/Reopen RULES/}).click();const reopened=page.getByTestId('reopened-review');await expect(reopened.getByRole('table')).toBeVisible();for(const photo of ['front','back']){await reopened.getByRole('group',{name:'Bottle photos'}).getByRole('button',{name:new RegExp(`${photo}.*${photo}.png`)}).click();for(const variant of ['Original upload','Normalized analysis image']){await reopened.getByRole('button',{name:variant,exact:true}).click();await expect(reopened.getByAltText(`${photo} · ${photo}.png · ${variant==='Original upload'?'original':'normalized'}`,{exact:true})).toBeVisible();}}expect(counters.executes).toBe(1);expect(counters.saves).toBe(1);
});
test('@integration grouped Batch keeps one review per bottle and invalidates a secondary edit',async({page})=>{
 const counters=await mock(page);await enter(page);await verifyAccess(page,code);await page.getByRole('tab',{name:'Batch upload',exact:true}).click();const panel=page.locator('#batch-panel'),mode=panel.getByLabel('Batch execution mode');if(await mode.count())await mode.selectOption('live');await panel.getByLabel('Batch label images',{exact:true}).setInputFiles(uploads);await panel.getByRole('tab',{name:'Application',exact:true}).click();const group={groupId:randomUUID(),application:base.application,photos:uploads.map((p,i)=>({photoId:randomUUID(),filename:p.name,role:i?'back':'front'}))};await panel.getByLabel('Application manifest file (JSON)').setInputFiles({name:'mapping.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({schemaVersion:2,groups:[group]}))});await panel.getByRole('button',{name:'Validate batch manifest'}).click();await expect(panel.getByTestId('manifest-counts')).toContainText('Valid: 1');await panel.getByRole('button',{name:'Start live batch',exact:true}).click();await expect(panel.getByTestId('batch-summary')).toContainText('Compared: 1');expect(counters.executes).toBe(1);await panel.getByRole('button',{name:'Open review',exact:true}).click();await expect(panel.getByTestId('active-pair').getByRole('table')).toBeVisible();await panel.getByText('Edit this bottle’s photos',{exact:true}).click();await panel.getByLabel('Role for back.png').selectOption('closeup');await expect(panel.getByTestId('active-pair').getByRole('table')).toHaveCount(0);await expect(panel.getByTestId('active-pair')).toContainText('Revision 2');expect(counters.executes).toBe(1);
});
